version: "3.9"

services:
  public:
    container_name: public-service
    build:
      context: ./public-service
    ports:
      - 3000:3000
    networks:
      - public
      - private

  subscription:
    container_name: subscription-service
    build:
      context: ./subscription-service
    ports:
      - 3001:3001
    networks:
      - private

  email:
    container_name: email-service
    build:
      context: ./email-service
    ports:
      - 3002:3002
    networks:
      - private

  mongo:
    container_name: mongodb-service
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    networks:
      - private
    command: --quiet

networks:
  public:
  private:
    internal: true
